import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getGridRows, gridApi, GridRow } from '../../api'
import AttachmentPanel from '../files/AttachmentPanel'

export default function ActivitiesPage() {
  const queryClient = useQueryClient()
  const [activityId, setActivityId] = useState(0)
  const [name, setName] = useState('')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [responsible, setResponsible] = useState(0)
  const [editingSubactivity, setEditingSubactivity] = useState<GridRow | null>(null)
  const [message, setMessage] = useState('')
  const activities = useQuery({ queryKey: ['all-activities'], queryFn: () => getGridRows('proyectos_actividades', '', {}, ['nombre']) })
  const users = useQuery({ queryKey: ['activity-users'], queryFn: () => getGridRows('users', '', { activo: true }, ['nombre', 'apellido']) })
  const subactivities = useQuery({ queryKey: ['subactivities', activityId], queryFn: () => getGridRows('proyectos_subactividades', '', { id_actividad: activityId }, ['nombre']), enabled: activityId > 0 })
  const save = useMutation({ mutationFn: () => editingSubactivity ? gridApi.update('proyectos_subactividades', { id: editingSubactivity.id, id_actividad: activityId, nombre: name, fecha_inicio: startDate || null, fecha_final: endDate || null }) : gridApi.insert('proyectos_subactividades', { id_actividad: activityId, nombre: name, fecha_inicio: startDate || null, fecha_final: endDate || null, estado: 0 }), onSuccess: () => { setName(''); setStartDate(''); setEndDate(''); setEditingSubactivity(null); setMessage('Subactividad guardada.'); queryClient.invalidateQueries({ queryKey: ['subactivities', activityId] }) }, onError: () => setMessage('No fue posible guardar la subactividad.') })
  const deactivate = useMutation({ mutationFn: (id: number) => gridApi.deactivate('proyectos_subactividades', id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['subactivities', activityId] }) })
  const assign = useMutation({ mutationFn: () => gridApi.update('proyectos_actividades', { id: activityId, id_responsable: responsible }), onSuccess: () => { setMessage('Responsable asignado.'); queryClient.invalidateQueries({ queryKey: ['all-activities'] }) } })

  function submit(event: FormEvent) { event.preventDefault(); if (startDate && endDate && endDate < startDate) { setMessage('La fecha final debe ser posterior a la inicial.'); return } save.mutate() }
  function edit(item: GridRow) { setEditingSubactivity(item); setName(String(item.nombre ?? '')); setStartDate(String(item.fecha_inicio ?? '').slice(0, 10)); setEndDate(String(item.fecha_final ?? '').slice(0, 10)) }
  function cancel() { setEditingSubactivity(null); setName(''); setStartDate(''); setEndDate('') }

  return <section><div className="topbar"><div><h1>Actividades y subactividades</h1><p className="muted">Gestiona el desglose de trabajo de los proyectos.</p></div></div><div className="panel"><label className="field">Actividad<select value={activityId} onChange={(event) => { setActivityId(Number(event.target.value)); cancel() }}><option value="0">Selecciona una actividad</option>{activities.data?.map((item: GridRow) => <option value={Number(item.id)} key={String(item.id)}>{String(item.nombre || item.id)}</option>)}</select></label>{activityId > 0 && <><form onSubmit={submit}><label className="field">{editingSubactivity ? 'Editar subactividad' : 'Nueva subactividad'}<input value={name} onChange={(event) => setName(event.target.value)} required /></label><div className="form-grid"><label className="field">Inicio<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label className="field">Fin<input type="date" min={startDate || undefined} value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div><button className="primary" disabled={save.isPending}>{editingSubactivity ? 'Guardar cambios' : 'Crear subactividad'}</button>{editingSubactivity && <button className="secondary" type="button" onClick={cancel}>Cancelar</button>}</form><label className="field">Responsable<select value={responsible} onChange={(event) => setResponsible(Number(event.target.value))}><option value="0">Selecciona un responsable</option>{users.data?.map((user: GridRow) => <option value={Number(user.id)} key={String(user.id)}>{String(user.nombre ?? '')} {String(user.apellido ?? '')}</option>)}</select></label><button className="secondary" onClick={() => assign.mutate()} disabled={!responsible || assign.isPending}>Asignar responsable</button></>}{message && <p className="muted" role="status">{message}</p>}</div><div className="panel"><h2>Subactividades</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Nombre</th><th>Inicio</th><th>Fin</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{subactivities.data?.map((item: GridRow, index) => <tr key={String(item.id ?? index)}><td>{String(item.id ?? '-')}</td><td>{String(item.nombre ?? '-')}</td><td>{String(item.fecha_inicio ?? '-')}</td><td>{String(item.fecha_final ?? '-')}</td><td>{String(item.estado ?? '-')}</td><td><button className="secondary" onClick={() => edit(item)}>Editar</button><button className="secondary" onClick={() => item.id && deactivate.mutate(item.id)} disabled={deactivate.isPending}>Desactivar</button></td></tr>)}</tbody></table></div></div>{activityId > 0 && <AttachmentPanel table="proyectos_actividades" id={activityId} />}</section>
}
