import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getGridRows, gridApi, GridRow } from '../../api'

type Activity = GridRow & { fecha_inicio?: string; fecha_final?: string }
type Draft = { fechaInicio: string; fechaFinal: string }
const dateValue = (value: unknown) => String(value ?? '').slice(0, 10)
const toDate = (value: unknown) => value ? new Date(String(value)) : null
const format = (value: unknown) => { const date = toDate(value); return date && !Number.isNaN(date.valueOf()) ? date.toLocaleDateString('es-CO') : 'Sin fecha' }

export default function GanttPage() {
  const queryClient = useQueryClient()
  const [projectId, setProjectId] = useState(0)
  const [drafts, setDrafts] = useState<Record<number, Draft>>({})
  const [message, setMessage] = useState('')
  const projects = useQuery({ queryKey: ['gantt-projects'], queryFn: () => getGridRows('proyectos', '', {}, ['codigo', 'nombre']) })
  const activities = useQuery({ queryKey: ['gantt-activities', projectId], queryFn: () => getGridRows('proyectos_actividades', '', { id_proyecto: projectId }, ['nombre']), enabled: projectId > 0 })
  const project = projects.data?.find((item) => Number(item.id) === projectId)
  const range = useMemo(() => { const start = toDate(project?.fecha_inicio); const end = toDate(project?.fecha_final); return start && end ? { start, days: Math.max(1, Math.ceil((end.valueOf() - start.valueOf()) / 86400000)) } : null }, [project])
  const save = useMutation({ mutationFn: ({ id, dates }: { id: number; dates: Draft }) => gridApi.update('proyectos_actividades', { id, fecha_inicio: dates.fechaInicio, fecha_final: dates.fechaFinal }), onSuccess: () => { setMessage('Planificación actualizada.'); queryClient.invalidateQueries({ queryKey: ['gantt-activities', projectId] }) }, onError: () => setMessage('No fue posible guardar las fechas del proyecto.') })
  const captureBaseline = useMutation({ mutationFn: async () => { const snapshot = (activities.data ?? []).map((item) => ({ id: item.id, nombre: item.nombre, fecha_inicio: item.fecha_inicio, fecha_final: item.fecha_final, id_responsable: item.id_responsable, porcentaje_avance: item.porcentaje_avance, presupuesto: item.presupuesto, gasto_realizado: item.gasto_realizado })); const json = JSON.stringify(snapshot); await gridApi.update('proyectos', { id: projectId, linea_base: json }); return gridApi.insert('proyectos_gantt_historico', { id_proyecto: projectId, json_gantt: json, fecha: new Date().toISOString().slice(0, 19).replace('T', ' '), activo: 1 }) }, onSuccess: () => { setMessage('Línea base registrada.'); queryClient.invalidateQueries({ queryKey: ['gantt-projects'] }) }, onError: () => setMessage('No fue posible registrar la línea base.') })
  function dates(item: Activity): Draft { return drafts[Number(item.id)] ?? { fechaInicio: dateValue(item.fecha_inicio), fechaFinal: dateValue(item.fecha_final) } }
  function updateDraft(id: number, field: keyof Draft, value: string) { setDrafts((current) => ({ ...current, [id]: { ...(current[id] ?? { fechaInicio: '', fechaFinal: '' }), [field]: value } })) }
  function position(item: Activity) { if (!range) return { left: '0%', width: '100%' }; const value = dates(item); const start = toDate(value.fechaInicio) || range.start; const end = toDate(value.fechaFinal) || start; const left = Math.max(0, (start.valueOf() - range.start.valueOf()) / 86400000); const width = Math.max(1, (end.valueOf() - start.valueOf()) / 86400000); return { left: `${Math.min(100, left / range.days * 100)}%`, width: `${Math.min(100, width / range.days * 100)}%` } }
  function saveActivity(item: Activity) { const value = dates(item); if (!value.fechaInicio || !value.fechaFinal || value.fechaFinal < value.fechaInicio) return setMessage('La fecha final debe ser posterior a la inicial.'); save.mutate({ id: Number(item.id), dates: value }) }
  return <section><div className="topbar"><div><h1>Gantt de proyectos</h1><p className="muted">Planifica actividades dentro del periodo del proyecto.</p></div></div><div className="panel"><label className="field">Proyecto<select value={projectId} onChange={(event) => { setProjectId(Number(event.target.value)); setDrafts({}); setMessage('') }}><option value="0">Selecciona un proyecto</option>{projects.data?.map((item) => <option value={Number(item.id)} key={String(item.id)}>{String(item.codigo || '')} {String(item.nombre || '')}</option>)}</select></label></div>{projectId > 0 && <div className="panel gantt"><div className="gantt-header">{range && <><span>{format(project?.fecha_inicio)} - {format(project?.fecha_final)}</span><span>Periodo: {range.days} días</span></>}<button className="secondary" onClick={() => captureBaseline.mutate()} disabled={captureBaseline.isPending || !activities.data?.length}>Capturar línea base</button></div>{message && <p className="muted" role="status">{message}</p>}{activities.data?.map((item, index) => { const value = dates(item as Activity); return <div className="gantt-row" key={String(item.id ?? index)}><div className="gantt-label">{String(item.nombre ?? `Actividad ${index + 1}`)}<small>{format(value.fechaInicio)} - {format(value.fechaFinal)}</small></div><div className="gantt-track"><span className="gantt-bar" style={position(item as Activity)} /></div><div className="form-grid"><label className="field">Inicio<input type="date" min={dateValue(project?.fecha_inicio) || undefined} max={dateValue(project?.fecha_final) || undefined} value={value.fechaInicio} onChange={(event) => updateDraft(Number(item.id), 'fechaInicio', event.target.value)} /></label><label className="field">Fin<input type="date" min={value.fechaInicio || undefined} max={dateValue(project?.fecha_final) || undefined} value={value.fechaFinal} onChange={(event) => updateDraft(Number(item.id), 'fechaFinal', event.target.value)} /></label><button className="secondary" onClick={() => saveActivity(item as Activity)} disabled={save.isPending}>Guardar</button></div></div>})}</div>}</section>
}