import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getGridRows, gridApi, GridRow } from '../../api'

function RelatedTable({ title, table, filter, columns }: { title: string; table: string; filter: Record<string, unknown>; columns: string[] }) {
  const rows = useQuery({ queryKey: ['project-related', table, filter], queryFn: () => getGridRows(table, '', filter, columns.filter((column) => column !== 'id')) })
  return <div className="related-section"><h3>{title}</h3>{rows.isLoading && <p className="muted">Cargando...</p>}<div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.data?.map((row: GridRow, index) => <tr key={String(row.id ?? index)}>{columns.map((column) => <td key={column}>{String(row[column] ?? '-')}</td>)}</tr>)}</tbody></table></div></div>
}

export default function ProjectsPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [projectId, setProjectId] = useState(0); const [activity, setActivity] = useState(''); const [risk, setRisk] = useState(''); const [message, setMessage] = useState(''); const projects = useQuery({ queryKey: ['projects', search], queryFn: () => getGridRows('proyectos', search, {}, ['codigo', 'nombre']) }); const createActivity = useMutation({ mutationFn: () => gridApi.insert('proyectos_actividades', { id_proyecto: projectId, nombre: activity, estado: 0 }), onSuccess: () => { setActivity(''); setMessage('Actividad creada.'); queryClient.invalidateQueries({ queryKey: ['project-related', 'proyectos_actividades'] }) }, onError: () => setMessage('No fue posible crear la actividad.') }); const createRisk = useMutation({ mutationFn: () => gridApi.insert('proyectos_riesgos', { id_proyecto: projectId, nombre: risk, estado: 0 }), onSuccess: () => { setRisk(''); setMessage('Riesgo creado.'); queryClient.invalidateQueries({ queryKey: ['project-related', 'proyectos_riesgos'] }) }, onError: () => setMessage('No fue posible crear el riesgo.') })
  function submitActivity(event: FormEvent) { event.preventDefault(); createActivity.mutate() }
  function submitRisk(event: FormEvent) { event.preventDefault(); createRisk.mutate() }
  return <section><div className="topbar"><div><h1>Proyectos</h1><p className="muted">Consulta proyectos, actividades y riesgos.</p></div><input className="search" placeholder="Buscar proyecto" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{projects.data?.map((project: GridRow, index) => <tr key={String(project.id ?? index)}><td>{String(project.codigo ?? '-')}</td><td>{String(project.nombre ?? '-')}</td><td>{String(project.estado ?? '-')}</td><td><button className="secondary" onClick={() => setProjectId(Number(project.id))}>Ver detalle</button></td></tr>)}</tbody></table></div></div>{projectId > 0 && <div className="panel project-detail"><h2>Detalle del proyecto #{projectId}</h2>{message && <p className="muted" role="status">{message}</p>}<div className="form-grid"><form onSubmit={submitActivity}><label className="field">Nueva actividad<input value={activity} onChange={(event) => setActivity(event.target.value)} required /></label><button className="primary" disabled={createActivity.isPending}>Crear actividad</button></form><form onSubmit={submitRisk}><label className="field">Nuevo riesgo<input value={risk} onChange={(event) => setRisk(event.target.value)} required /></label><button className="primary" disabled={createRisk.isPending}>Crear riesgo</button></form></div><RelatedTable title="Actividades" table="proyectos_actividades" filter={{ id_proyecto: projectId }} columns={['id', 'nombre', 'fecha_inicio', 'fecha_final']} /><RelatedTable title="Riesgos" table="proyectos_riesgos" filter={{ id_proyecto: projectId }} columns={['id', 'nombre', 'descripcion', 'mitigacion']} /></div>}</section>
}
