import { ChangeEvent, FormEvent, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Paperclip, X } from 'lucide-react'
import { requestQueries } from './request-api'
import { fileApi } from '../../api'
import RichTextEditor from '../../components/RichTextEditor'

type Option = { id: number; nombre: string }

function Options({ items }: { items?: Option[] }) {
  return <><option value="0">Selecciona una opción</option>{items?.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</>
}

export default function RequestPage() {
  const [module, setModule] = useState('incidencias'); const [area, setArea] = useState(0); const [category, setCategory] = useState(0); const [subcategory, setSubcategory] = useState(0); const [urgency, setUrgency] = useState(0); const [impact, setImpact] = useState(0); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [files, setFiles] = useState<File[]>([]); const [message, setMessage] = useState(''); const [submitting, setSubmitting] = useState(false)
  const areas = useQuery({ queryKey: ['request-areas', module], queryFn: () => requestQueries.areas(module) }); const categories = useQuery({ queryKey: ['request-categories', area], queryFn: () => requestQueries.categories(area), enabled: area > 0 }); const subcategories = useQuery({ queryKey: ['request-subcategories', category], queryFn: () => requestQueries.subcategories(category), enabled: category > 0 }); const urgencies = useQuery({ queryKey: ['urgencies'], queryFn: requestQueries.urgencies }); const impacts = useQuery({ queryKey: ['impacts'], queryFn: requestQueries.impacts })
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); setSubmitting(true); try { const response = await requestQueries.create({ modulo: module, area, categoria: category, subcategoria: subcategory, urgencia: urgency, impacto: impact, asunto: subject, descripcion: description }); const failedUploads: string[] = []; for (const file of files) { try { await fileApi.upload(file, module === 'servicios' ? 'servicios' : 'incidencias', response.id) } catch { failedUploads.push(file.name) } } const ticket = `Ticket #${response.id}`; const assignmentMessage = response.assignment?.msg === 'success' ? ' Fue asignado automáticamente.' : ' Quedó pendiente de asignación.'; setMessage(failedUploads.length ? `${ticket} creado, pero no se pudieron adjuntar: ${failedUploads.join(', ')}.${assignmentMessage}` : files.length ? `${ticket} creado con sus archivos adjuntos.${assignmentMessage}` : `${ticket} creado correctamente.${assignmentMessage}`); setSubject(''); setDescription(''); setFiles([]) } catch { setMessage('No fue posible crear la solicitud.') } finally { setSubmitting(false) } }
  function selectFiles(event: ChangeEvent<HTMLInputElement>) { setFiles((current) => [...current, ...Array.from(event.target.files ?? [])]); event.target.value = '' }
  function changeModule(value: string) { setModule(value); setArea(0); setCategory(0); setSubcategory(0) }
  function changeArea(value: number) { setArea(value); setCategory(0); setSubcategory(0) }
  function changeCategory(value: number) { setCategory(value); setSubcategory(0) }
  return <section><div className="topbar"><div><h1>Nueva solicitud</h1><p className="muted">Registra una incidencia, problema o servicio.</p></div></div><form className="panel request-form" onSubmit={submit}><div className="form-grid"><label className="field">Tipo<select value={module} onChange={(event) => changeModule(event.target.value)}><option value="incidencias">Incidencia</option><option value="problemas">Problema</option><option value="servicios">Servicio</option></select></label><label className="field">Urgencia<select value={urgency} onChange={(event) => setUrgency(Number(event.target.value))} required><Options items={urgencies.data} /></select></label><label className="field">Impacto<select value={impact} onChange={(event) => setImpact(Number(event.target.value))} required><Options items={impacts.data} /></select></label><label className="field">Área<select value={area} onChange={(event) => changeArea(Number(event.target.value))} required><Options items={areas.data} /></select></label><label className="field">Categoría<select value={category} onChange={(event) => changeCategory(Number(event.target.value))} required><Options items={categories.data} /></select></label><label className="field">Subcategoría<select value={subcategory} onChange={(event) => setSubcategory(Number(event.target.value))} required><Options items={subcategories.data} /></select></label></div><label className="field">Asunto<input value={subject} onChange={(event) => setSubject(event.target.value)} required maxLength={255} /></label><label className="field">Descripción<RichTextEditor value={description} onChange={setDescription} /></label><div className="request-attachments"><label className="attachment-picker"><Paperclip size={18} aria-hidden="true" />Adjuntar archivos<input type="file" multiple onChange={selectFiles} /></label>{files.length > 0 && <div className="queued-files">{files.map((file, index) => <div className="queued-file" key={`${file.name}-${index}`}><Paperclip size={16} aria-hidden="true" /><span><strong>{file.name}</strong><small>{Math.ceil(file.size / 1024)} KB</small></span><button type="button" aria-label={`Quitar ${file.name}`} onClick={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))}><X size={14} aria-hidden="true" /></button></div>)}</div>}</div>{message && <p className="request-status" role="status">{message}</p>}<button className="primary" type="submit" disabled={submitting}>{submitting ? 'Creando solicitud...' : 'Crear solicitud'}</button></form></section>
}
