import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getGridRows, requestApi, GridRow } from '../../api'
import { Link } from 'react-router-dom'

const columns = ['id', 'asunto', 'estado', 'prioridad']

export default function RequestBoardPage({ table, title, type, filter = {} }: { table: string; title: string; type: string; filter?: Record<string, unknown> }) {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('-id'); const [message, setMessage] = useState(''); const queryClient = useQueryClient(); const useV1Requests = ['incidencia', 'problema', 'servicio'].includes(type)
  const requestRows = useQuery({ queryKey: ['v1-requests', type, search, page, sort], queryFn: () => ({ incidencia: requestApi.listIncidents, problema: requestApi.listProblems, servicio: requestApi.listServices }[type] || requestApi.listIncidents)({ page, per_page: 25, search, sort }), enabled: useV1Requests })
  const legacyRows = useQuery({ queryKey: ['request-board', table, type, search, filter], queryFn: () => getGridRows(table, search, filter, ['asunto', 'descripcion']), enabled: !useV1Requests })
  const records: GridRow[] = useV1Requests ? (requestRows.data?.data || []) : (legacyRows.data || [])
  const meta = useV1Requests ? requestRows.data?.meta : undefined
  const isLoading = useV1Requests ? requestRows.isLoading : legacyRows.isLoading
  const isError = useV1Requests ? requestRows.isError : legacyRows.isError
  const isLoaded = useV1Requests ? requestRows.data !== undefined : legacyRows.data !== undefined
  const assign = useMutation({ mutationFn: (id: number) => requestApi.assign(id, type), onSuccess: (data) => { setMessage(data.msg === 'success' ? 'Solicitud asignada correctamente.' : `Resultado: ${data.msg}`); queryClient.invalidateQueries({ queryKey: ['request-board'] }) }, onError: () => setMessage('No fue posible asignar la solicitud.') })
  const manage = useMutation({ mutationFn: (id: number) => requestApi.manage({ tabla: table, opcion: type, idRow: id, estado: 2, estadoActual: 1, name_estado: 'En proceso', observacion: 'Solicitud puesta en proceso.' }), onSuccess: () => { setMessage('Solicitud actualizada.'); queryClient.invalidateQueries({ queryKey: ['request-board'] }) }, onError: () => setMessage('No fue posible actualizar la solicitud.') })
  return <section><div className="topbar"><div><h1>{title}</h1><p className="muted">Gestiona solicitudes y asignaciones.</p></div><input className="search" placeholder="Buscar" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} /></div><div className="panel">{message && <p className="muted" role="status">{message}</p>}{isLoading && <p className="muted">Cargando solicitudes...</p>}{isError && <div className="error">No fue posible cargar las solicitudes.</div>}{isLoaded && <><div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{useV1Requests && column !== 'id' ? <button className="table-sort" type="button" onClick={() => { setSort((current) => current === column ? `-${column}` : column); setPage(1) }}>{column}<span aria-hidden="true">{sort === column ? ' ↑' : sort === `-${column}` ? ' ↓' : ''}</span></button> : column}</th>)}<th>Acciones</th></tr></thead><tbody>{records.map((row: GridRow, index) => <tr key={String(row.id ?? index)}>{columns.map((column) => <td key={column}>{String(row[column] ?? '-')}</td>)}<td><Link className="secondary" to={`/solicitudes/${table}/${row.id}`}>Detalle</Link><button className="secondary" onClick={() => row.id && assign.mutate(row.id)} disabled={assign.isPending}>Asignar</button><button className="secondary" onClick={() => row.id && manage.mutate(row.id)} disabled={manage.isPending}>En proceso</button></td></tr>)}</tbody></table></div>{meta && <div className="table-pagination"><span>{meta.total} {title.toLowerCase()}</span><div><button className="secondary" type="button" onClick={() => setPage((current) => current - 1)} disabled={page === 1}>Anterior</button><span>Página {meta.current_page} de {meta.last_page}</span><button className="secondary" type="button" onClick={() => setPage((current) => current + 1)} disabled={page === meta.last_page}>Siguiente</button></div></div>}</>}</div></section>
}