import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { requestApi, GridRow } from '../../api'
import { Link } from 'react-router-dom'

const columns = ['id', 'asunto', 'estado', 'prioridad']

export default function RequestBoardPage({ title, type }: { title: string; type: 'incidencia' | 'problema' | 'servicio' }) {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('-id'); const [message, setMessage] = useState(''); const queryClient = useQueryClient(); const table = type === 'servicio' ? 'servicios' : 'incidencias'
  const commands = { incidencia: { list: requestApi.listIncidents, assign: requestApi.assignIncident, start: requestApi.startIncident }, problema: { list: requestApi.listProblems, assign: requestApi.assignProblem, start: requestApi.startProblem }, servicio: { list: requestApi.listServices, assign: requestApi.assignService, start: requestApi.startService } }[type]
  const requestRows = useQuery({ queryKey: ['v1-requests', type, search, page, sort], queryFn: () => commands.list({ page, per_page: 25, search, sort }) })
  const records: GridRow[] = requestRows.data?.data || []
  const meta = requestRows.data?.meta
  const assign = useMutation({ mutationFn: (id: number) => commands.assign(id), onSuccess: (data) => { setMessage(data.msg === 'success' ? 'Solicitud asignada correctamente.' : `Resultado: ${data.msg}`); queryClient.invalidateQueries({ queryKey: ['v1-requests'] }) }, onError: () => setMessage('No fue posible asignar la solicitud.') })
  const manage = useMutation({ mutationFn: (id: number) => commands.start(id), onSuccess: () => { setMessage('Solicitud actualizada.'); queryClient.invalidateQueries({ queryKey: ['v1-requests'] }) }, onError: () => setMessage('No fue posible actualizar la solicitud.') })
  return <section><div className="topbar"><div><h1>{title}</h1><p className="muted">Gestiona solicitudes y asignaciones.</p></div><input className="search" placeholder="Buscar" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} /></div><div className="panel">{message && <p className="muted" role="status">{message}</p>}{requestRows.isLoading && <p className="muted">Cargando solicitudes...</p>}{requestRows.isError && <div className="error">No fue posible cargar las solicitudes.</div>}{requestRows.data !== undefined && <><div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column !== 'id' ? <button className="table-sort" type="button" onClick={() => { setSort((current) => current === column ? `-${column}` : column); setPage(1) }}>{column}<span aria-hidden="true">{sort === column ? ' ↑' : sort === `-${column}` ? ' ↓' : ''}</span></button> : column}</th>)}<th>Acciones</th></tr></thead><tbody>{records.map((row: GridRow, index) => <tr key={String(row.id ?? index)}>{columns.map((column) => <td key={column}>{String(row[column] ?? '-')}</td>)}<td><Link className="secondary" to={`/solicitudes/${table}/${row.id}`}>Detalle</Link><button className="secondary" onClick={() => row.id && assign.mutate(row.id)} disabled={assign.isPending}>Asignar</button><button className="secondary" onClick={() => row.id && manage.mutate(row.id)} disabled={manage.isPending}>En proceso</button></td></tr>)}</tbody></table></div>{meta && <div className="table-pagination"><span>{meta.total} {title.toLowerCase()}</span><div><button className="secondary" type="button" onClick={() => setPage((current) => current - 1)} disabled={page === 1}>Anterior</button><span>Página {meta.current_page} de {meta.last_page}</span><button className="secondary" type="button" onClick={() => setPage((current) => current + 1)} disabled={page === meta.last_page}>Siguiente</button></div></div>}</>}</div></section>
}