import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getGridRows, gridApi, GridRow, notificationApi } from '../../api'
import { useAuth } from '../../auth'

type Form = { iniciativa: string; nombre: string; descripcion: string; orden: string }
const emptyForm: Form = { iniciativa: '', nombre: '', descripcion: '', orden: '1' }

export default function CommitteesPage() {
  const { session } = useAuth(); const queryClient = useQueryClient(); const [form, setForm] = useState<Form>(emptyForm); const [committee, setCommittee] = useState<GridRow | null>(null); const [userId, setUserId] = useState(0); const [message, setMessage] = useState('')
  const committees = useQuery({ queryKey: ['initiative-committees'], queryFn: () => getGridRows('iniciativas_comites', '', {}, ['nombre']) }); const initiatives = useQuery({ queryKey: ['committee-initiatives'], queryFn: () => getGridRows('iniciativas', '', {}, ['codigo', 'nombre']) }); const users = useQuery({ queryKey: ['committee-users'], queryFn: () => getGridRows('users', '', { activo: true }, ['nombre', 'apellido']) }); const approvers = useQuery({ queryKey: ['committee-approvers', committee?.id], queryFn: () => getGridRows('iniciativas_comites_aprobadores', '', { id_comite: committee?.id, activo: true }, ['id_user']), enabled: Boolean(committee?.id) })
  const save = useMutation({ mutationFn: () => gridApi.insert('iniciativas_comites', { id_iniciativa: Number(form.iniciativa), nombre: form.nombre, descripcion: form.descripcion, orden: Number(form.orden), estado_validacion: 1, activo: 1 }), onSuccess: () => { setForm(emptyForm); setMessage('Comité creado.'); queryClient.invalidateQueries({ queryKey: ['initiative-committees'] }) }, onError: () => setMessage('No fue posible crear el comité.') })
  const addApprover = useMutation({ mutationFn: () => gridApi.insert('iniciativas_comites_aprobadores', { id_comite: Number(committee?.id), id_iniciativa: Number(committee?.id_iniciativa), id_user: userId, estado_validacion: 1, activo: 1 }), onSuccess: () => { setUserId(0); setMessage('Aprobador agregado.'); queryClient.invalidateQueries({ queryKey: ['committee-approvers', committee?.id] }) }, onError: () => setMessage('No fue posible agregar el aprobador.') })
  const removeApprover = useMutation({ mutationFn: (id: number) => gridApi.deactivate('iniciativas_comites_aprobadores', id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['committee-approvers', committee?.id] }) })
  const notify = useMutation({ mutationFn: (committeeId: number) => notificationApi.committee(committeeId, session?.userData?.id || 0), onSuccess: () => setMessage('Solicitud enviada a los aprobadores.'), onError: () => setMessage('No fue posible notificar al comité.') })
  const assigned = new Set((approvers.data ?? []).map((item) => Number(item.id_user)))
  function field(key: keyof Form, value: string) { setForm((current) => ({ ...current, [key]: value })) }
  function submit(event: FormEvent) { event.preventDefault(); save.mutate() }
  return <section><div className="topbar"><div><h1>Comités de iniciativas</h1><p className="muted">Define etapas, aprobadores y solicitudes de validación.</p></div></div><div className="panel"><form onSubmit={submit}><div className="form-grid"><label className="field">Iniciativa<select value={form.iniciativa} onChange={(event) => field('iniciativa', event.target.value)} required><option value="">Selecciona iniciativa</option>{initiatives.data?.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.codigo ?? '')} {String(item.nombre)}</option>)}</select></label><label className="field">Nombre<input value={form.nombre} onChange={(event) => field('nombre', event.target.value)} required /></label><label className="field">Descripción<textarea value={form.descripcion} onChange={(event) => field('descripcion', event.target.value)} required /></label><label className="field">Orden<input type="number" min="1" value={form.orden} onChange={(event) => field('orden', event.target.value)} required /></label></div><button className="primary" disabled={save.isPending}>Crear comité</button></form></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Iniciativa</th><th>Nombre</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{committees.data?.map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.id_iniciativa ?? '-')}</td><td>{String(item.nombre ?? '-')}</td><td>{String(item.estado_validacion ?? '-')}</td><td><button className="secondary" onClick={() => { setCommittee(item); setUserId(0) }}>Aprobadores</button><button className="secondary" onClick={() => item.id && notify.mutate(Number(item.id))}>Notificar</button></td></tr>)}</tbody></table></div></div>{committee && <div className="panel"><h2>Aprobadores: {String(committee.nombre)}</h2><label className="field">Usuario<select value={userId} onChange={(event) => setUserId(Number(event.target.value))}><option value="0">Selecciona un aprobador</option>{users.data?.filter((item) => !assigned.has(Number(item.id))).map((item) => <option value={Number(item.id)} key={String(item.id)}>{String(item.nombre)} {String(item.apellido)}</option>)}</select></label><button className="primary" onClick={() => addApprover.mutate()} disabled={!userId || addApprover.isPending}>Agregar aprobador</button>{message && <p className="muted" role="status">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Usuario</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{approvers.data?.map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.id_user ?? '-')}</td><td>{String(item.estado_validacion ?? '-')}</td><td><button className="secondary" onClick={() => item.id && removeApprover.mutate(Number(item.id))}>Retirar</button></td></tr>)}</tbody></table></div></div>}</section>
}