import { FormEvent, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import { initiativeApi } from '../../api'

export default function InitiativeValidationPage() {
  const { idRow = '0', idComite = '0', idUser = '0', uuid = '' } = useParams(); const [decision, setDecision] = useState('2'); const [observation, setObservation] = useState(''); const [message, setMessage] = useState(''); const status = useQuery({ queryKey: ['initiative-validation', idRow, uuid], queryFn: () => initiativeApi.status(Number(idRow), uuid) }); const save = useMutation({ mutationFn: async () => { const data = { estado_validacion: Number(decision), observaciones_validacion: observation, fecha_validacion: new Date().toISOString() }; await initiativeApi.saveValidation(Number(idRow), data, uuid); return initiativeApi.saveFollowup({ id_maestro: Number(idRow), id_aprobador: Number(idUser), id_comite: Number(idComite), estado: decision === '2' ? 'Aprobada' : 'Rechazada', observacion: observation, fecha: new Date().toISOString() }, uuid) }, onSuccess: () => setMessage('Validación guardada correctamente.'), onError: () => setMessage('No fue posible guardar la validación.') })
  function submit(event: FormEvent) { event.preventDefault(); save.mutate() }
  return <main className="auth-shell"><section className="auth-card"><div className="brand">IKAROS / MANAGEMENT</div><h1>Validar iniciativa</h1><p className="muted">Revisa la información antes de registrar tu decisión.</p>{status.isLoading && <p className="muted">Cargando iniciativa...</p>}{status.data?.[0] && <div className="detail-item"><span>Iniciativa</span><strong>#{String(status.data[0].id_iniciativa)}</strong></div>}<form onSubmit={submit}><label className="field">Decisión<select value={decision} onChange={(event) => setDecision(event.target.value)}><option value="2">Aprobar</option><option value="3">Rechazar</option></select></label><label className="field">Observaciones<textarea rows={5} value={observation} onChange={(event) => setObservation(event.target.value)} required /></label>{message && <p className="muted" role="status">{message}</p>}<button className="primary" disabled={save.isPending}>Guardar decisión</button></form></section></main>
}