import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { catalogApi, GridRow, locationApi, Location } from '../../api'

export default function LocationsPage() {
  const queryClient = useQueryClient(); const [departmentId, setDepartmentId] = useState(''); const [name, setName] = useState(''); const [editing, setEditing] = useState<Location | null>(null); const [message, setMessage] = useState('')
  const departments = useQuery({ queryKey: ['v1-location-departments'], queryFn: () => catalogApi.list('departments') }); const locations = useQuery({ queryKey: ['v1-locations'], queryFn: locationApi.list })
  const save = useMutation({ mutationFn: () => editing ? locationApi.update(editing.id, { id_departamento: Number(departmentId), nombre: name }) : locationApi.create({ id_departamento: Number(departmentId), nombre: name }), onSuccess: () => { setDepartmentId(''); setName(''); setEditing(null); setMessage('Ubicación guardada.'); queryClient.invalidateQueries({ queryKey: ['v1-locations'] }) }, onError: () => setMessage('No fue posible guardar la ubicación.') })
  const deactivate = useMutation({ mutationFn: (id: number) => locationApi.deactivate(id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['v1-locations'] }) })
  function submit(event: FormEvent) { event.preventDefault(); save.mutate() }
  function edit(item: Location) { setEditing(item); setDepartmentId(String(item.id_departamento)); setName(item.nombre); setMessage('') }
  return <section><div className="topbar"><div><h1>Ubicaciones</h1><p className="muted">Administra ubicaciones asociadas a departamentos.</p></div></div><div className="panel"><form onSubmit={submit}><div className="form-grid"><label className="field">Departamento<select value={departmentId} onChange={(event) => setDepartmentId(event.target.value)} required><option value="">Selecciona departamento</option>{departments.data?.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.nombre)}</option>)}</select></label><label className="field">Ubicación<input value={name} onChange={(event) => setName(event.target.value)} required /></label></div>{message && <p className="muted" role="status">{message}</p>}<button className="primary" disabled={save.isPending}>{editing ? 'Guardar cambios' : 'Crear ubicación'}</button>{editing && <button className="secondary" type="button" onClick={() => { setEditing(null); setDepartmentId(''); setName('') }}>Cancelar</button>}</form></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Departamento</th><th>Ubicación</th><th>Acciones</th></tr></thead><tbody>{locations.data?.map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.id_departamento ?? '-')}</td><td>{String(item.nombre ?? '-')}</td><td><button className="secondary" onClick={() => edit(item)}>Editar</button><button className="secondary" onClick={() => item.id && deactivate.mutate(Number(item.id))}>Desactivar</button></td></tr>)}</tbody></table></div></div></section>
}