import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { thirdPartySurveyQuestionApi, ThirdPartySurveyQuestion } from '../../api'

export default function ThirdPartySurveyQuestionsPage() {
  const queryClient = useQueryClient(); const [type, setType] = useState<ThirdPartySurveyQuestion['tipo']>('cliente'); const [name, setName] = useState(''); const [editing, setEditing] = useState<ThirdPartySurveyQuestion | null>(null); const [message, setMessage] = useState('')
  const questions = useQuery({ queryKey: ['v1-third-party-survey-questions', type], queryFn: () => thirdPartySurveyQuestionApi.list(type) })
  const save = useMutation({ mutationFn: () => editing ? thirdPartySurveyQuestionApi.update(editing.id, { tipo: type, nombre: name }) : thirdPartySurveyQuestionApi.create({ tipo: type, nombre: name }), onSuccess: () => { setEditing(null); setName(''); setMessage('Pregunta guardada.'); queryClient.invalidateQueries({ queryKey: ['v1-third-party-survey-questions', type] }) }, onError: () => setMessage('No fue posible guardar la pregunta.') })
  const deactivate = useMutation({ mutationFn: (id: number) => thirdPartySurveyQuestionApi.deactivate(id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['v1-third-party-survey-questions', type] }) })
  function submit(event: FormEvent) { event.preventDefault(); save.mutate() }
  return <section><div className="topbar"><div><h1>Preguntas de terceros</h1><p className="muted">Configura las preguntas para encuestas de clientes y proveedores.</p></div></div><div className="panel"><label className="field">Tipo<select value={type} onChange={(event) => { setType(event.target.value as typeof type); setEditing(null); setName('') }}><option value="cliente">Cliente</option><option value="proveedor">Proveedor</option></select></label><form onSubmit={submit}><label className="field">Pregunta<input value={name} onChange={(event) => setName(event.target.value)} maxLength={255} required /></label>{message && <p className="muted" role="status">{message}</p>}<button className="primary" disabled={save.isPending}>{editing ? 'Guardar cambios' : 'Crear pregunta'}</button>{editing && <button className="secondary" type="button" onClick={() => { setEditing(null); setName('') }}>Cancelar</button>}</form></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Pregunta</th><th>Acciones</th></tr></thead><tbody>{questions.data?.map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.nombre ?? '-')}</td><td><button className="secondary" onClick={() => { setEditing(item); setName(String(item.nombre ?? '')) }}>Editar</button><button className="secondary" onClick={() => item.id && deactivate.mutate(Number(item.id))}>Desactivar</button></td></tr>)}</tbody></table></div></div></section>
}