import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CatalogResource, catalogApi, GridRow } from '../../api'

type Props = { resource: CatalogResource; title: string; description: string; fields: string[]; sensitiveFields?: string[] }

export default function CatalogPage({ resource, title, description, fields, sensitiveFields = [] }: Props) {
  const displayFields = fields.filter((field) => !sensitiveFields.includes(field))
  const queryClient = useQueryClient(); const [values, setValues] = useState<Record<string, string>>({}); const [editingId, setEditingId] = useState<number | null>(null); const [message, setMessage] = useState(''); const rows = useQuery({ queryKey: ['v1-catalog', resource], queryFn: () => catalogApi.list(resource) })
  const save = useMutation({ mutationFn: () => { const payload = editingId ? Object.fromEntries(Object.entries(values).filter(([field, value]) => !sensitiveFields.includes(field) || value !== '')) : values; return editingId ? catalogApi.update(resource, editingId, payload) : catalogApi.create(resource, payload) }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['v1-catalog', resource] }); setValues({}); setEditingId(null); setMessage(editingId ? 'Registro actualizado.' : 'Registro creado correctamente.') }, onError: () => setMessage('No fue posible guardar el registro.') })
  const deactivate = useMutation({ mutationFn: (id: number) => catalogApi.deactivate(resource, id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['v1-catalog', resource] }) })
  function submit(event: FormEvent) { event.preventDefault(); save.mutate() }
  function edit(row: GridRow) { setEditingId(Number(row.id)); setValues(Object.fromEntries(fields.map((field) => [field, String(row[field] ?? '')]))); setMessage('') }
  function cancel() { setEditingId(null); setValues({}) }
  return <section><div className="topbar"><div><h1>{title}</h1><p className="muted">{description}</p></div></div><div className="panel"><form onSubmit={submit}><div className="form-grid">{fields.map((field) => <label className="field" key={field}>{field}<input type={sensitiveFields.includes(field) ? 'password' : 'text'} value={values[field] || ''} onChange={(event) => setValues({ ...values, [field]: event.target.value })} required={!editingId || !sensitiveFields.includes(field)} /></label>)}</div>{message && <p className="muted" role="status">{message}</p>}<button className="primary" disabled={save.isPending}>{editingId ? 'Guardar cambios' : 'Crear registro'}</button>{editingId && <button className="secondary" type="button" onClick={cancel}>Cancelar</button>}</form></div><div className="panel"><div className="table-wrap"><table><thead><tr>{displayFields.map((field) => <th key={field}>{field}</th>)}<th>Acciones</th></tr></thead><tbody>{rows.data?.map((row, index) => <tr key={String(row.id ?? index)}>{displayFields.map((field) => <td key={field}>{String(row[field] ?? '-')}</td>)}<td><button className="secondary" onClick={() => edit(row)}>Editar</button><button className="secondary" onClick={() => row.id && deactivate.mutate(row.id)} disabled={deactivate.isPending}>Desactivar</button></td></tr>)}</tbody></table></div></div></section>
}
